{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNhmnRV9eKFbHwf/3fvLfGE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "24dddbe6ef3b42cabeb66a65c709cdd9": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "VBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "VBoxModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "VBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_4a8e4c3b1ee54534bd6168663f31eb33",
              "IPY_MODEL_95d8d40102fb4c0ea44637c50d9d42ab",
              "IPY_MODEL_900bb8461bc54ddc82fb14f4ffb22677",
              "IPY_MODEL_0349a23dd15c485c84e33229cde8a117",
              "IPY_MODEL_ab56a4dd426548e7b27a62495366a0b0",
              "IPY_MODEL_2ff46169eb7f461c8d94d05e3b97bd90",
              "IPY_MODEL_c7e71047d5ba4f9790642a8008fba261",
              "IPY_MODEL_f9b32fc4c8d44c589e73e1f53d53cea6",
              "IPY_MODEL_8aed3d62399f4af3a30d49e7efab3668",
              "IPY_MODEL_6015dcf353b047fba9be86119250c890"
            ],
            "layout": "IPY_MODEL_a3dc5ccf87204bf797dc6f8267cc3295"
          }
        },
        "4a8e4c3b1ee54534bd6168663f31eb33": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Age",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_6c6d254ec5c14b4f900d511c4b4dccf0",
            "max": 80,
            "min": 18,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_975817a39d074a55bae6d8927d1ce064",
            "value": 25
          }
        },
        "95d8d40102fb4c0ea44637c50d9d42ab": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Weight kg",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_8c1db63f3a2c470e901dd3c6619d362d",
            "max": 120,
            "min": 40,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_4d7de8763cde4fd0be732525524c4723",
            "value": 65
          }
        },
        "900bb8461bc54ddc82fb14f4ffb22677": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Height cm",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_4f19800a19e34be383f6a6c8084d0d84",
            "max": 200,
            "min": 140,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_bf9f66c8b2544f0ba09c53280e596f62",
            "value": 170
          }
        },
        "0349a23dd15c485c84e33229cde8a117": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Cigarettes",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_11e8795f20ee42a084985223b27c746e",
            "max": 30,
            "min": 0,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_fea5d04c59ce483ba4bf8f4cecdf0a7b",
            "value": 0
          }
        },
        "ab56a4dd426548e7b27a62495366a0b0": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Alcohol",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_b309b33ea6b54fb5bd8737aae5594009",
            "max": 10,
            "min": 0,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_4a0bb606160f41c39c2d18818a4c7235",
            "value": 0
          }
        },
        "2ff46169eb7f461c8d94d05e3b97bd90": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "FloatSliderView",
            "continuous_update": true,
            "description": "Distance km",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_a476e010c9954c4cabef1484a1b7f0b0",
            "max": 15,
            "min": 0,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": ".2f",
            "step": 0.1,
            "style": "IPY_MODEL_43d4e74ddf92498eb7af196c73673d13",
            "value": 0
          }
        },
        "c7e71047d5ba4f9790642a8008fba261": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "FloatSliderView",
            "continuous_update": true,
            "description": "Sleep hrs",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_6ec341b4ef684dc4bf452c153e40b014",
            "max": 12,
            "min": 0,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": ".2f",
            "step": 0.1,
            "style": "IPY_MODEL_ea1d8da5a70440adad001b5318213c58",
            "value": 7
          }
        },
        "f9b32fc4c8d44c589e73e1f53d53cea6": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Calories",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_22d34bc7e073462ba6ea1bc901ddb0c4",
            "max": 4000,
            "min": 1200,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_8b4ecef94b1144a8ab215ee118766276",
            "value": 2000
          }
        },
        "8aed3d62399f4af3a30d49e7efab3668": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "IntSliderModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "IntSliderModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "IntSliderView",
            "continuous_update": true,
            "description": "Caffeine mg",
            "description_tooltip": null,
            "disabled": false,
            "layout": "IPY_MODEL_b6602729a09c43f387facd273c44297a",
            "max": 600,
            "min": 0,
            "orientation": "horizontal",
            "readout": true,
            "readout_format": "d",
            "step": 1,
            "style": "IPY_MODEL_9a3fc70ecb7849d39f9476eb06bbe43c",
            "value": 100
          }
        },
        "6015dcf353b047fba9be86119250c890": {
          "model_module": "@jupyter-widgets/output",
          "model_name": "OutputModel",
          "model_module_version": "1.0.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/output",
            "_model_module_version": "1.0.0",
            "_model_name": "OutputModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/output",
            "_view_module_version": "1.0.0",
            "_view_name": "OutputView",
            "layout": "IPY_MODEL_78a30b17d9244973b22f92cdbeb499e3",
            "msg_id": "",
            "outputs": [
              {
                "output_type": "display_data",
                "data": {
                  "text/plain": "<Figure size 600x300 with 1 Axes>",
                  "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjMAAAEpCAYAAABm96OiAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAAQZ9JREFUeJzt3XdYFFf/NvB7aUtHpaM0wUosEaNY0QiiRmNv0YiKNZagSYw8TzTRqKhJFNtjS8SeqFGJKRZs2BtG7NhAbCCKgIDCwp73D17m5woIq7vA6v25Lq6LOTNz5rvDDtzMnNmRCSEEiIiIiHSUXnkXQERERPQmGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiuHm5obBgweXdxlqO3jwIGQyGQ4ePFjepZTou+++g0wmU2vZR48evda22rRpg/fee++11iWiio1hhnTK6tWrIZPJpC9jY2PUrFkTY8eORVJSUnmXp5ZZs2YhIiKi3LZfsC/PnDlT5Pzy+uNf3vvlTb34/nzxy8HBobxLI3prGZR3AUSvY/r06XB3d8fz589x5MgRLF26FP/88w8uXrwIU1NTjWwjNjYWenray/uzZs1Cr1690K1bN61tQxe9DfvF398fgwYNUmkzMTEpp2qI3n4MM6STOnbsiMaNGwMAhg0bBmtra8ybNw9//PEH+vfvX+Q6mZmZMDMzK/U25HK5Rmqld0/NmjUxcODAUi0rhMDz588ZdojeAC8z0Vvhww8/BADExcUBAAYPHgxzc3PcvHkTnTp1goWFBQYMGAAgP9R88cUXcHZ2hlwuR61atfDjjz/i5QfIFzVmJjU1FcHBwdK6np6emDNnDpRKpcpySqUSCxYsQL169WBsbAxbW1t06NBBuqQjk8mQmZmJNWvWSJchXtzWvXv3MHToUNjb20Mul8PLywurVq0q9Lrv3r2Lbt26wczMDHZ2dpgwYQKys7PfaF+WZP369fD29oaJiQmqVKmCfv364c6dOyrLHD58GL1794aLiwvkcjmcnZ0xYcIEPHv27JV9l7RfgPyfweDBg1GpUiVYWVlhyJAhyMrKKnX90dHRaN68OUxMTODu7o5ly5ZJ8zIyMmBmZobPP/+80Hp3796Fvr4+QkNDS72tori5uaFz587YvXs3GjduDBMTEyxfvlx6baV5fxXsAysrK1SqVAmBgYE4d+4cZDIZVq9eLS3Xpk0btGnTplANgwcPhpubm0qbUqlEWFgYvLy8YGxsDHt7e4wcORJPnjwpsv4jR46gSZMmMDY2RvXq1bF27dpC20lNTcWECRPg5uYGuVyOatWqYdCgQXj06FGZ7Gt6d/DMDL0Vbt68CQCwtraW2nJzcxEQEICWLVvixx9/hKmpKYQQ+Pjjj3HgwAEEBQWhYcOG2L17N7766ivcu3cP8+fPL3YbWVlZ8PX1xb179zBy5Ei4uLjg2LFjCAkJwYMHDxAWFiYtGxQUhNWrV6Njx44YNmwYcnNzcfjwYZw4cQKNGzfGunXrMGzYMDRp0gQjRowAAHh4eAAAkpKS4OPjA5lMhrFjx8LW1hY7d+5EUFAQ0tPTERwcDAB49uwZ2rVrh4SEBIwfPx5OTk5Yt24d9u/fr9a+S0tLK3JQrUKhKNQ2c+ZMTJkyBX369MGwYcOQnJyMRYsWoXXr1vj3339RqVIlAMCWLVuQlZWF0aNHw9raGqdOncKiRYtw9+5dbNmypdhaXrVfCvTp0wfu7u4IDQ3F2bNn8fPPP8POzg5z5swp8bU+efIEnTp1Qp8+fdC/f39s3rwZo0ePhpGREYYOHQpzc3N0794dmzZtwrx586Cvry+t++uvv0IIIYXiV3n+/HmhfWphYSGd7YuNjUX//v0xcuRIDB8+HLVq1Sr1+0sIga5du+LIkSMYNWoU6tSpg+3btyMwMLDEul5l5MiRWL16NYYMGYLx48cjLi4Oixcvxr///oujR4/C0NBQWvbGjRvo1asXgoKCEBgYiFWrVmHw4MHw9vaGl5cXgPxg2KpVK1y5cgVDhw5Fo0aN8OjRI+zYsQN3795Fw4YNNbKviQAAgkiHhIeHCwBi7969Ijk5Wdy5c0f89ttvwtraWpiYmIi7d+8KIYQIDAwUAMTkyZNV1o+IiBAAxIwZM1Tae/XqJWQymbhx44bU5urqKgIDA6Xp77//XpiZmYlr166prDt58mShr68vEhIShBBC7N+/XwAQ48ePL1S/UqmUvjczM1Ppv0BQUJBwdHQUjx49Umnv16+fsLKyEllZWUIIIcLCwgQAsXnzZmmZzMxM4enpKQCIAwcOFOr7RQX78lVfXl5e0vLx8fFCX19fzJw5U6WfCxcuCAMDA5X2ghpfFBoaKmQymbh9+7bU9u2334qXfw0Vt18Klh06dKhKe/fu3YW1tfUrX6sQQvj6+goA4qeffpLasrOzRcOGDYWdnZ3IyckRQgixe/duAUDs3LlTZf369esLX1/fErdT3L4MDw8XQuS/rwCIXbt2qaxX2vdXwXt47ty50jK5ubmiVatWKtspeM1F1RwYGChcXV2l6cOHDwsAYsOGDSrL7dq1q1B7Qf2HDh2S2h4+fCjkcrn44osvpLapU6cKAGLbtm2Ftl9wHLzpviYqwMtMpJP8/Pxga2sLZ2dn9OvXD+bm5ti+fTuqVq2qstzo0aNVpv/55x/o6+tj/PjxKu1ffPEFhBDYuXNnsdvcsmULWrVqhcqVK+PRo0fSl5+fH/Ly8nDo0CEAwNatWyGTyfDtt98W6qOk25CFENi6dSu6dOkCIYTKdgICApCWloazZ89Kr8XR0RG9evWS1jc1NZXOaJTWkiVLEBkZWeirfv36Kstt27YNSqUSffr0UanLwcEBNWrUwIEDB6RlXxz/kZmZiUePHqF58+YQQuDff/9Vq76XjRo1SmW6VatWePz4MdLT00tc18DAACNHjpSmjYyMMHLkSDx8+BDR0dEA8t9bTk5O2LBhg7TcxYsXcf78+VKPg+natWuh/RkQECDNd3d3V5kGSv/++ueff2BgYKDy3tbX18e4ceNKVVtRtmzZAisrK/j7+6ts29vbG+bm5io/WwCoW7cuWrVqJU3b2tqiVq1auHXrltS2detWNGjQAN27dy+0vYLjQBP7mgjgZSbSUUuWLEHNmjVhYGAAe3t71KpVq9CdRwYGBqhWrZpK2+3bt+Hk5AQLCwuV9jp16kjzi3P9+nWcP38etra2Rc5/+PAhgPxLXk5OTqhSpYrarys5ORmpqalYsWIFVqxY8crt3L59G56enoUCUq1atdTaZpMmTaTB1C8q+KNa4Pr16xBCoEaNGkX28+JliISEBEydOhU7duwoNOYiLS1Nrfpe5uLiUqhOIP8SkqWl5SvXdXJyKjQIvGbNmgCA+Ph4+Pj4QE9PDwMGDMDSpUuRlZUFU1NTbNiwAcbGxujdu3epaqxWrRr8/PyKne/u7l6orbTvr9u3b8PR0RHm5uYq89X9ub+87bS0NNjZ2b1y2wVe/hkA+T+HF3/WN2/eRM+ePV+5XU3sayKAYYZ0VHF/gF8kl8s1emu1UqmEv78/Jk2aVOT8gj+Kb7oNABg4cGCxYyBePmNSVpRKJWQyGXbu3KkyvqFAwR/XvLw8+Pv7IyUlBV9//TVq164NMzMz3Lt3D4MHDy40mFVdRW0bQKEB3G9i0KBB+OGHHxAREYH+/ftj48aN6Ny5M6ysrDTSf1F3Lmnj/SWTyYrcL3l5eYW2bWdnp3KG5EUvByxN/gy0va/p3cAwQ+8UV1dX7N27F0+fPlU5O3P16lVpfnE8PDyQkZHxyv+4C5bbvXs3UlJSXnl2pqhLTra2trCwsEBeXl6J23F1dcXFixchhFDpKzY29pXrvS4PDw8IIeDu7v7KP6wXLlzAtWvXsGbNGpXPWomMjCzVdkr7icCv4/79+4Vu0b927RoAqNzd89577+H999/Hhg0bUK1aNSQkJGDRokVaqwso/fvL1dUV+/btQ0ZGhsrZmaJ+7pUrV1a59FPg5TOQHh4e2Lt3L1q0aKGxW8Q9PDxw8eLFEpcrj31Nbx+OmaF3SqdOnZCXl4fFixertM+fPx8ymQwdO3Ysdt0+ffrg+PHj2L17d6F5qampyM3NBQD07NkTQghMmzat0HIv/udqZmaG1NRUlfn6+vro2bMntm7dWuQfguTkZJXXcv/+ffz+++9SW1ZWVrGXp95Ujx49oK+vj2nTphX6D1wIgcePH0uvoaDtxfkLFiwo1XaK2i+akpubK90GDQA5OTlYvnw5bG1t4e3trbLsp59+ij179iAsLAzW1tavfG9oQmnfX506dUJubi6WLl0qzc/LyysyAHh4eODq1asq75uYmBgcPXq00Lbz8vLw/fffF+ojNzf3tX4ePXv2RExMDLZv315o3svvn7Le1/T24ZkZeqd06dIFbdu2xX//+1/Ex8ejQYMG2LNnD/744w8EBwcXug34RV999RV27NiBzp07S7ehZmZm4sKFC/j9998RHx8PGxsbtG3bFp9++ikWLlyI69evo0OHDlAqlTh8+DDatm2LsWPHAgC8vb2xd+9ezJs3D05OTnB3d0fTpk0xe/ZsHDhwAE2bNsXw4cNRt25dpKSk4OzZs9i7dy9SUlIAAMOHD8fixYsxaNAgREdHw9HREevWrdPYJyC/zMPDAzNmzEBISAji4+PRrVs3WFhYIC4uDtu3b8eIESPw5Zdfonbt2vDw8MCXX36Je/fuwdLSElu3bi00dqY4xe0XTXBycsKcOXMQHx+PmjVrYtOmTTh37hxWrFihMuYHAD755BNMmjQJ27dvx+jRowvN17TSvr+6dOmCFi1aYPLkyYiPj0fdunWxbdu2IsciDR06FPPmzUNAQACCgoLw8OFDLFu2DF5eXioDpn19fTFy5EiEhobi3LlzaN++PQwNDXH9+nVs2bIFCxYsUBloXtrX8/vvv6N3794YOnQovL29kZKSgh07dmDZsmVo0KCBtGxZ72t6C5X5/VNEb6DgduLTp0+/crnAwEBhZmZW5LynT5+KCRMmCCcnJ2FoaChq1KghfvjhB5XbpoUofGt2wbohISHC09NTGBkZCRsbG9G8eXPx448/Srf2CpF/q+wPP/wgateuLYyMjIStra3o2LGjiI6Olpa5evWqaN26tTAxMREAVLaVlJQkxowZI5ydnYWhoaFwcHAQ7dq1EytWrFCp5/bt2+Ljjz8WpqamwsbGRnz++efS7bSlvTW7uH3p6+urcmt2ga1bt4qWLVsKMzMzYWZmJmrXri3GjBkjYmNjpWUuX74s/Pz8hLm5ubCxsRHDhw8XMTExhW4dLurW7OL2S8GyycnJRb6OuLi4V77egtdz5swZ0axZM2FsbCxcXV3F4sWLi12nU6dOAoA4duzYK/t+EQAxZsyYYue7urqKjz76qMh5pX1/PX78WHz66afC0tJSWFlZiU8//VT8+++/hfavEEKsX79eVK9eXRgZGYmGDRuK3bt3F7o1u8CKFSuEt7e3MDExERYWFqJevXpi0qRJ4v79+yXWX9Rt4I8fPxZjx44VVatWFUZGRqJatWoiMDCw0McOCPF6+5qogEwIDY6aI3qLODs7IyAgAD///HN5l0LlpHv37rhw4QJu3LhR3qWUKD4+Hu7u7ggPD9fJp73r0r6miodjZoiKoFAo8PjxY9jY2JR3KVROHjx4gL///huffvppeZfy1uO+pjfFMTNEL9m9ezd+++036XEB9G6Ji4vD0aNH8fPPP8PQ0FDlQ/ZIs7ivSVMYZoheMnv2bNy4cQMzZ86Ev79/eZdDZSwqKgpDhgyBi4sL1qxZAwcHh/Iu6a3FfU2aUq5jZg4dOoQffvgB0dHRePDgAbZv345u3bpJ84UQ+Pbbb7Fy5UqkpqaiRYsWWLp0qconkKakpGDcuHH4888/oaenh549e2LBggWFPh2TiIiI3k7lOmYmMzMTDRo0wJIlS4qcP3fuXCxcuBDLli3DyZMnYWZmhoCAADx//lxaZsCAAbh06RIiIyPx119/4dChQ2o/m4aIiIh0V4W5m0kmk6mcmRFCwMnJCV988QW+/PJLAPnPdLG3t8fq1avRr18/XLlyBXXr1sXp06elj7bftWsXOnXqhLt378LJyam8Xg4RERGVkQo7ZiYuLg6JiYkqH+1tZWWFpk2b4vjx4+jXrx+OHz+OSpUqqTyjx8/PD3p6ejh58mSRT2sFgOzsbGRnZ0vTSqUSKSkpsLa21upHqRMREb1thBB4+vQpnJycNPo8PHVU2DCTmJgIALC3t1dpt7e3l+YlJiYWesqrgYEBqlSpIi1TlNDQ0CI/ap6IiIhez507d1CtWrVy2XaFDTPaFBISgokTJ0rTaWlpcHFxQVxcnMrDB9+EQqHAgQMH0LZtW340N5WZp9lPEZ0YjZN3T+Lk/ZM4ff80nimeqSxjqG+I9x3eR9OqTeFT1QdNnJqgsknlcqq4ZDyWiDRHG8fT06dP4e7urrG/n6+jwoaZglv0kpKS4OjoKLUnJSWhYcOG0jIPHz5UWS83NxcpKSmvvMVPLpdDLpcXaq9SpQosLS01UH3+G8bU1BTW1tb8BUxlxhrWcHNyQ89GPQEAijwFYpJicCThiPSVlJmEU49P4dTjU1h0Pv/hhF62Xmjp0lL6crVyrTCXXHksEWmONo6ngn7K83dGhQ0z7u7ucHBwwL59+6Twkp6ejpMnT2L06NEAgGbNmiE1NRXR0dHSE2/3798PpVKpsQfTEekyQ31DNHZqjMZOjRHsEwwhBG4+uakSbmIfx+JS8iVcSr6E5dH5T5SualFVCjYtnFugvn196Ovpl/OrISIqWrmGmYyMDJXncMTFxeHcuXOoUqUKXFxcEBwcjBkzZqBGjRpwd3fHlClT4OTkJN3xVKdOHXTo0AHDhw/HsmXLoFAoMHbsWPTr1493MhEVQSaTwbOKJzyreGJww8EAgOTMZBy9c1QKN9EPonHv6T1surQJmy5tAgBYGFmgmXMztHTODzhNqzWFqaF2ns5NRKSucg0zZ86cQdu2baXpgnEsgYGBWL16NSZNmoTMzEyMGDECqampaNmyJXbt2gVjY2NpnQ0bNmDs2LFo166d9KF5CxcuLPPXQqSrbM1s0a12N3Sr3Q0AkKXIwul7p/PDzZ0jOHbnGNKz07Hn5h7subkHAGCgZ4BGjo2kcNPCpQXszOxesRUiIu2pMJ8zU57S09NhZWWFtLQ0jY6Z+eeff9CpUyde5yedlqfMw8WHF6Vwc/j2Ydx7eq/QcjWta0rhpqVLS3hW8dTINXQeS0Sao43jSRt/Q9VVYcfMEFHFoK+njwYODdDAoQHGNBkDIQQS0hL+b9zNnSO4+PAirj2+hmuPr2HVuVUAADszu/xg8/8DTkOHhjDUZxghIs1jmCEitchkMrhWcoVrJVcMqD8AAJDyLAXH7xyXws2pe6fwMPMhtl3Zhm1XtgEATA1N4VPNRwo3PtV8YCF/9a2ceco8RN2OwqEnh2B22wxtq7flQGQiKoRhhojeWBWTKvio5kf4qOZHAIDnuc8RfT8aRxKOSIOLnzx/gv1x+7E/bj8AQE+mh4YODdHCuYV0acrJ4v8G7m+7sg2f7/ocd9PvAgDm3Z6HapbVsKDDAvSo06PsXyQRVVgMM0SkccYGxmjh0gItXFoAAJRCiauPrqrcEh6XGoezD87i7IOzWHQq//Nu3Cu5o6VLS5gammJF9AoIqA7pu5d+D70298LvfX5noCEiCcMMEWmdnkwPdW3roq5tXYzwzn+q/b30eyq3hMckxSAuNQ5xqXHF9lMQbobvGI7MnEyYGprC2MAYcgM5jA2M87/Xf+H7/98u15fDSN+ownwQIBFpFsMMEZWLqpZV0cerD/p49QEApGen48TdE1h/fj3WnV/3ynVTnqdgUMQgtbdZXNgptl2/FMuo0S7Xl3PMD5EWMMwQUYVgKbdEe4/2eJz1uMQwAwDv2b2HSsaVkJ2bjee5z/E89zmy8/K/L2jLzstWWadgubTsNG29jBIZ6hmW6kySSpv+6weootoN9Ax4loreKgwzRFShOFo4lrwQgEUdF6GNW5tXLiOEQE5eTqGw82LgUbs9T/11lUIp1aRQKqDIUSAjJ+NNdtMbkUH2+meYShO+StGf3EAOPZleue2Dd9HbfHcgwwwRVSitXFqhmmU13Eu/V2gAMJD/h7iaZTW0cmlVYl8ymSz/8o6BHFaw0ka5pZKrzH2tEPXKZfPU6y8nL0eqR0DgWe4zPMt99oqqtc9I36hcLvu92Gag9278GXzb7w58N36KRKQz9PX0saDDAvTa3AsyyFQCjQz5l0bCOoTp1H+UBnoGMDcyh7mRebnVoBRKZOdma+bs1MvtaoSyF3+eOXk5yMnLwdOcp+W2X/RkeuqHIw1f9tP24PRtV7ah1+Zeb/XdgQwzRFTh9KjTA7/3+V3lP0kAqGZZDWEdwnT+F2950JPpwcTQBCaGJuVWgxBC9SxVOV32y1XmSjUphRJZiixkKbLKbb8AKHTW6HUv+RU1PmrU36OKPMspICCDDMG7gtG1Vled+gfhZQwzRFQh9ajTA11rdcWBWwew88hOdGzZ8a26xv8ukslkMNQ3hKG+YYmf/qxNecq80l3KUydYqXnZ73nuc5WasvPyz5ohu5iitURA4E76HRxOOFziGLSKjGGGiCosfT19+Lr6IvNSJnxdfRlkSCP09fRhqmcKU0PTcquhYHC6ti/73Uu/h+sp10us58HTB2XwqrWHYYaIiKiMvTg43VKuvSdNH4w/iLZr2pa4XGnvIqyoeF8cERHRW6rg7sCCwfMvk0EGZ0vnUt0dWJExzBAREb2lCu4OBFAo0Ojq3YFFYZghIiJ6ixXcHVjVsqpKezXLam/FbdkAx8wQERG99d72uwMZZoiIiN4Bb/PdgbzMRERERDqNYYaIiIh0GsMMERER6TSGGSIiItJpDDNERESk0xhmiIiISKcxzBAREZFOY5ghIiIincYwQ0RERDqNYYaIiIh0GsMMERER6TSGGSIiItJpDDNERESk0xhmiIiISKcxzBAREZFOY5ghIiIinVahw0xeXh6mTJkCd3d3mJiYwMPDA99//z2EENIyQghMnToVjo6OMDExgZ+fH65fv16OVRMREVFZqtBhZs6cOVi6dCkWL16MK1euYM6cOZg7dy4WLVokLTN37lwsXLgQy5Ytw8mTJ2FmZoaAgAA8f/68HCsnIiKismJQ3gW8yrFjx9C1a1d89NFHAAA3Nzf8+uuvOHXqFID8szJhYWH45ptv0LVrVwDA2rVrYW9vj4iICPTr16/caiciIqKyUaHDTPPmzbFixQpcu3YNNWvWRExMDI4cOYJ58+YBAOLi4pCYmAg/Pz9pHSsrKzRt2hTHjx8vNsxkZ2cjOztbmk5PTwcAKBQKKBQKjdRe0I+m+iN6V/FYItIcbRxPFeHYrNBhZvLkyUhPT0ft2rWhr6+PvLw8zJw5EwMGDAAAJCYmAgDs7e1V1rO3t5fmFSU0NBTTpk0r1L5nzx6Ymppq8BUAkZGRGu2P6F3FY4lIczR5PGVlZWmsr9dVocPM5s2bsWHDBmzcuBFeXl44d+4cgoOD4eTkhMDAwNfuNyQkBBMnTpSm09PT4ezsjPbt28PS0lITpUOhUCAyMhL+/v4wNDTUSJ9E7yIeS0Sao43jqeDqRnmq0GHmq6++wuTJk6XLRfXq1cPt27cRGhqKwMBAODg4AACSkpLg6OgorZeUlISGDRsW269cLodcLi/UbmhoqPFfltrok+hdxGOJSHM0eTxVhOOyQt/NlJWVBT091RL19fWhVCoBAO7u7nBwcMC+ffuk+enp6Th58iSaNWtWprUSERFR+ajQZ2a6dOmCmTNnwsXFBV5eXvj3338xb948DB06FAAgk8kQHByMGTNmoEaNGnB3d8eUKVPg5OSEbt26lW/xREREVCYqdJhZtGgRpkyZgs8++wwPHz6Ek5MTRo4cialTp0rLTJo0CZmZmRgxYgRSU1PRsmVL7Nq1C8bGxuVYOREREZWVCh1mLCwsEBYWhrCwsGKXkclkmD59OqZPn152hREREVGFUaHHzBARERGVhGGGiIiIdBrDDBEREek0hhkiIiLSaQwzREREpNMYZoiIiEinMcwQERGRTmOYISIiIp3GMENEREQ6jWGGiIiIdBrDDBEREek0hhkiIiLSaQwzREREpNMYZoiIiEinMcwQERGRTmOYISIiIp3GMENEREQ6jWGGiIiIdBrDDBEREem01w4zOTk5iI2NRW5uribrISIiIlKL2mEmKysLQUFBMDU1hZeXFxISEgAA48aNw+zZszVeIBEREdGrqB1mQkJCEBMTg4MHD8LY2Fhq9/Pzw6ZNmzRaHBEREVFJDNRdISIiAps2bYKPjw9kMpnU7uXlhZs3b2q0OCIiIqKSqH1mJjk5GXZ2doXaMzMzVcINERERUVlQO8w0btwYf//9tzRdEGB+/vlnNGvWTHOVEREREZWC2peZZs2ahY4dO+Ly5cvIzc3FggULcPnyZRw7dgxRUVHaqJGIiIioWGqfmWnZsiViYmKQm5uLevXqYc+ePbCzs8Px48fh7e2tjRqJiIiIiqXWmRmFQoGRI0diypQpWLlypbZqIiIiIio1tc7MGBoaYuvWrdqqhYiIiEhtal9m6tatGyIiIrRQChEREZH61B4AXKNGDUyfPh1Hjx6Ft7c3zMzMVOaPHz9eY8URERERlUTtMPPLL7+gUqVKiI6ORnR0tMo8mUzGMENERERlSu0wExcXp406iIiIiF7Laz81GwCEEBBCaKoWIiIiIrW9VphZu3Yt6tWrBxMTE5iYmKB+/fpYt26dpmsjIiIiKpHaYWbevHkYPXo0OnXqhM2bN2Pz5s3o0KEDRo0ahfnz52u8wHv37mHgwIGwtraGiYkJ6tWrhzNnzkjzhRCYOnUqHB0dYWJiAj8/P1y/fl3jdRAREVHFpPaYmUWLFmHp0qUYNGiQ1Pbxxx/Dy8sL3333HSZMmKCx4p48eYIWLVqgbdu22LlzJ2xtbXH9+nVUrlxZWmbu3LlYuHAh1qxZA3d3d0yZMgUBAQG4fPkyjI2NNVYLERERVUxqh5kHDx6gefPmhdqbN2+OBw8eaKSoAnPmzIGzszPCw8OlNnd3d+l7IQTCwsLwzTffoGvXrgDyL4HZ29sjIiIC/fr102g9REREVPGofZnJ09MTmzdvLtS+adMm1KhRQyNFFdixYwcaN26M3r17w87ODu+//77KYxTi4uKQmJgIPz8/qc3KygpNmzbF8ePHNVoLERERVUxqn5mZNm0a+vbti0OHDqFFixYAgKNHj2Lfvn1Fhpw3cevWLSxduhQTJ07Ef/7zH5w+fRrjx4+HkZERAgMDkZiYCACwt7dXWc/e3l6aV5Ts7GxkZ2dL0+np6QDynz2lUCg0UntBP5rqj+hdxWOJSHO0cTxVhGNT7TDTs2dPnDx5EvPnz5cea1CnTh2cOnUK77//vkaLUyqVaNy4MWbNmgUAeP/993Hx4kUsW7YMgYGBr91vaGgopk2bVqh9z549MDU1fe1+ixIZGanR/ojeVTyWiDRHk8dTVlaWxvp6XWqHGQDw9vbG+vXrNV1LIY6Ojqhbt65KW506daSHXTo4OAAAkpKS4OjoKC2TlJSEhg0bFttvSEgIJk6cKE2np6fD2dkZ7du3h6WlpUZqVygUiIyMhL+/PwwNDTXSJ9G7iMcSkeZo43gquLpRntQOM//88w/09fUREBCg0r57924olUp07NhRY8W1aNECsbGxKm3Xrl2Dq6srgPzBwA4ODti3b58UXtLT03Hy5EmMHj262H7lcjnkcnmhdkNDQ43/stRGn0TvIh5LRJqjyeOpIhyXag8Anjx5MvLy8gq1CyEwefJkjRRVYMKECThx4gRmzZqFGzduYOPGjVixYgXGjBkDIP9ZUMHBwZgxYwZ27NiBCxcuYNCgQXByckK3bt00WgsRERFVTGqfmbl+/XqhSz8AULt2bdy4cUMjRRX44IMPsH37doSEhGD69Olwd3dHWFgYBgwYIC0zadIkZGZmYsSIEUhNTUXLli2xa9cufsYMERHRO0LtMGNlZYVbt27Bzc1Npf3GjRswMzPTVF2Szp07o3PnzsXOl8lkmD59OqZPn67xbRMREVHFp/Zlpq5duyI4OBg3b96U2m7cuIEvvvgCH3/8sUaLIyIiIiqJ2mFm7ty5MDMzQ+3ateHu7g53d3fUqVMH1tbW+PHHH7VRIxEREVGxXusy07FjxxAZGYmYmBjpqdmtW7fWRn1EREREr/RanzMjk8nQvn17tG/fXtP1EBEREaml1JeZjh8/jr/++kulbe3atXB3d4ednR1GjBih8ogAIiIiorJQ6jAzffp0XLp0SZq+cOECgoKC4Ofnh8mTJ+PPP/9EaGioVookIiIiKk6pw8y5c+fQrl07afq3335D06ZNsXLlSkycOBELFy7U+IMmiYiIiEpS6jDz5MkTladTR0VFqTy64IMPPsCdO3c0Wx0RERFRCUodZuzt7REXFwcAyMnJwdmzZ+Hj4yPNf/r0aYV4PgMRERG9W0odZjp16oTJkyfj8OHDCAkJgampKVq1aiXNP3/+PDw8PLRSJBEREVFxSn1r9vfff48ePXrA19cX5ubmWLNmDYyMjKT5q1at4q3aREREVOZKHWZsbGxw6NAhpKWlwdzcHPr6+irzt2zZAnNzc40XSERERPQqr/UJwEWpUqXKGxdDREREpC61n81EREREVJEwzBAREZFOY5ghIiIincYwQ0RERDrttZ6aff36dRw4cAAPHz6EUqlUmTd16lSNFEZERERUGmqHmZUrV2L06NGwsbGBg4MDZDKZNE8mkzHMEBERUZlSO8zMmDEDM2fOxNdff62NeoiIiIjUovaYmSdPnqB3797aqIWIiIhIbWqHmd69e2PPnj3aqIWIiIhIbaW6zLRw4ULpe09PT0yZMgUnTpxAvXr1Cj0pe/z48ZqtkIiIiOgVShVm5s+frzJtbm6OqKgoREVFqbTLZDKGGSIiIipTpQozcXFx2q6DiIiI6LWoPWZm+vTpyMrKKtT+7NkzTJ8+XSNFEREREZWW2mFm2rRpyMjIKNSelZWFadOmaaQoIiIiotJSO8wIIVQ+KK9ATEwMqlSpopGiiIiIiEqr1B+aV7lyZchkMshkMtSsWVMl0OTl5SEjIwOjRo3SSpFERERExSl1mAkLC4MQAkOHDsW0adNgZWUlzTMyMoKbmxuaNWumlSKJiIiIilPqMBMYGAgAcHd3R/PmzQt9vgwRERFReShVmElPT5e+f//99/Hs2TM8e/asyGUtLS01UxkRERFRKZQqzFSqVKnIQb8vKhgYnJeXp5HCiIiIiEqjVGHmwIED2q6DiIiI6LWUKsz4+vpquw4iIiKi16L258wUyMrKwtWrV3H+/HmVL22aPXs2ZDIZgoODpbbnz59jzJgxsLa2hrm5OXr27ImkpCSt1kFEREQVR6nvZiqQnJyMIUOGYOfOnUXO19aYmdOnT2P58uWoX7++SvuECRPw999/Y8uWLbCyssLYsWPRo0cPHD16VCt1EBERUcWi9pmZ4OBgpKam4uTJkzAxMcGuXbuwZs0a1KhRAzt27NBGjcjIyMCAAQOwcuVKVK5cWWpPS0vDL7/8gnnz5uHDDz+Et7c3wsPDcezYMZw4cUIrtRAREVHFonaY2b9/P+bNm4fGjRtDT08Prq6uGDhwIObOnYvQ0FBt1IgxY8bgo48+gp+fn0p7dHQ0FAqFSnvt2rXh4uKC48ePa6UWIiIiqljUvsyUmZkJOzs7APmPOEhOTkbNmjVRr149nD17VuMF/vbbbzh79ixOnz5daF5iYiKMjIxQqVIllXZ7e3skJiYW22d2djays7Ol6YLP0VEoFFAoFBqpu6AfTfVH9K7isUSkOdo4nirCsal2mKlVqxZiY2Ph5uaGBg0aYPny5XBzc8OyZcvg6Oio0eLu3LmDzz//HJGRkTA2NtZYv6GhoUU+4XvPnj0wNTXV2HYAIDIyUqP9Eb2reCwRaY4mj6esrCyN9fW6ZEIIoc4K69evR25uLgYPHozo6Gh06NABKSkpMDIywurVq9G3b1+NFRcREYHu3btDX19fasvLy4NMJoOenh52794NPz8/PHnyROXsjKurK4KDgzFhwoQi+y3qzIyzszMePXqksU8wVigUiIyMhL+/Px/9QPQGeCwRaY42jqf09HTY2NggLS2t3J4CoPaZmYEDB0rfe3t74/bt27h69SpcXFxgY2Oj0eLatWuHCxcuqLQNGTIEtWvXxtdffw1nZ2cYGhpi37596NmzJwAgNjYWCQkJr3zopVwuh1wuL9RuaGio8V+W2uiT6F3EY4lIczR5PFWE41LtMFMgJycHcXFx8PDwQKNGjTRZk8TCwgLvvfeeSpuZmRmsra2l9qCgIEycOBFVqlSBpaUlxo0bh2bNmsHHx0crNREREVHFovbdTFlZWQgKCoKpqSm8vLyQkJAAABg3bhxmz56t8QJLMn/+fHTu3Bk9e/ZE69at4eDggG3btpV5HURERFQ+1A4zISEhiImJwcGDB1UG5fr5+WHTpk0aLa4oBw8eRFhYmDRtbGyMJUuWICUlBZmZmdi2bRscHBy0XgcRERFVDGpfZoqIiMCmTZvg4+Oj8iRtLy8v3Lx5U6PFEREREZVE7TMzycnJ0ufMvCgzM1Ml3BARERGVBbXDTOPGjfH3339L0wUB5ueff37lHURERERE2qD2ZaZZs2ahY8eOuHz5MnJzc7FgwQJcvnwZx44dQ1RUlDZqJCIiIiqW2mdmWrZsiXPnziE3Nxf16tXDnj17YGdnh+PHj8Pb21sbNRIREREV67U+Z8bDwwMrV67UdC1EREREait1mCl4GGNJyuujjImIiOjdVOowU6lSpVferSSEgEwmQ15enkYKIyIiIiqNUoeZAwcOSN8LIdCpUyf8/PPPqFq1qlYKIyIiIiqNUocZX19flWl9fX34+PigevXqGi+KiIiIqLTUvpuJiIiIqCJhmCEiIiKd9kZhho8vICIiovJW6jEzPXr0UJl+/vw5Ro0aBTMzM5X2bdu2aaYyIiIiolIodZixsrJSmR44cKDGiyEiIiJSV6nDTHh4uDbrICIiInotHABMREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkVOsyEhobigw8+gIWFBezs7NCtWzfExsaqLPP8+XOMGTMG1tbWMDc3R8+ePZGUlFROFRMREVFZq9BhJioqCmPGjMGJEycQGRkJhUKB9u3bIzMzU1pmwoQJ+PPPP7FlyxZERUXh/v376NGjRzlWTURERGXJoLwLeJVdu3apTK9evRp2dnaIjo5G69atkZaWhl9++QUbN27Ehx9+CAAIDw9HnTp1cOLECfj4+JRH2URERFSGKnSYeVlaWhoAoEqVKgCA6OhoKBQK+Pn5ScvUrl0bLi4uOH78eLFhJjs7G9nZ2dJ0eno6AEChUEChUGik1oJ+NNUf0buKxxKR5mjjeKoIx6bOhBmlUong4GC0aNEC7733HgAgMTERRkZGqFSpksqy9vb2SExMLLav0NBQTJs2rVD7nj17YGpqqtG6IyMjNdof0buKxxKR5mjyeMrKytJYX69LZ8LMmDFjcPHiRRw5cuSN+woJCcHEiROl6fT0dDg7O6N9+/awtLR84/6B/KQaGRkJf39/GBoaaqRPoncRjyUizdHG8VRwdaM86USYGTt2LP766y8cOnQI1apVk9odHByQk5OD1NRUlbMzSUlJcHBwKLY/uVwOuVxeqN3Q0FDjvyy10SfRu4jHEpHmaPJ4qgjHZYW+m0kIgbFjx2L79u3Yv38/3N3dVeZ7e3vD0NAQ+/btk9piY2ORkJCAZs2alXW5REREVA4q9JmZMWPGYOPGjfjjjz9gYWEhjYOxsrKCiYkJrKysEBQUhIkTJ6JKlSqwtLTEuHHj0KxZM97JRERE9I6o0GFm6dKlAIA2bdqotIeHh2Pw4MEAgPnz50NPTw89e/ZEdnY2AgIC8L///a+MKyUiIqLyUqHDjBCixGWMjY2xZMkSLFmypAwqIiIiooqmQo+ZISIiIioJwwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mkMM0RERKTTGGaIiIhIpzHMEBERkU5jmCEiIiKdxjBDREREOo1hhoiIiHQawwwRERHpNIYZIiIi0mlvTZhZsmQJ3NzcYGxsjKZNm+LUqVPlXRIRERGVgbcizGzatAkTJ07Et99+i7Nnz6JBgwYICAjAw4cPy7s0IiIi0rK3IszMmzcPw4cPx5AhQ1C3bl0sW7YMpqamWLVqVXmXRkRERFpmUN4FvKmcnBxER0cjJCREatPT04Ofnx+OHz9e5DrZ2dnIzs6WptPS0gAAKSkpUCgUGqlLoVAgKysLjx8/hqGhoUb6JHoX8Vgi0hxtHE9Pnz4FAAghNNLf69D5MPPo0SPk5eXB3t5epd3e3h5Xr14tcp3Q0FBMmzatULu7u7tWaiQiInrbPX36FFZWVuWybZ0PM68jJCQEEydOlKaVSiVSUlJgbW0NmUymkW2kp6fD2dkZd+7cgaWlpUb6JHoX8Vgi0hxtHE9CCDx9+hROTk4a6e916HyYsbGxgb6+PpKSklTak5KS4ODgUOQ6crkccrlcpa1SpUpaqc/S0pK/gIk0gMcSkeZo+ngqrzMyBXR+ALCRkRG8vb2xb98+qU2pVGLfvn1o1qxZOVZGREREZUHnz8wAwMSJExEYGIjGjRujSZMmCAsLQ2ZmJoYMGVLepREREZGWvRVhpm/fvkhOTsbUqVORmJiIhg0bYteuXYUGBZcluVyOb7/9ttDlLCJSD48lIs15W48nmSjPe6mIiIiI3pDOj5khIiKidxvDDBEREek0hhkiIiLSaQwzWrZ69WqVz7D57rvv0LBhw3Krh4heD49d0nVubm4ICwsr023Gx8dDJpPh3LlzAICDBw9CJpMhNTVVo9thmCnG4MGDIZPJIJPJYGhoCHt7e/j7+2PVqlVQKpWl7qdv3764du2aFisl0owX3/MvfnXo0KG8SyPSCXfu3MHQoUPh5OQEIyMjuLq64vPPP8fjx4/LuzQAwOnTpzFixIjyLkMrGGZeoUOHDnjw4AHi4+Oxc+dOtG3bFp9//jk6d+6M3NzcUvVhYmICOzs7LVdKpBkF7/kXv3799VetbU8IUepjiagiu3XrFho3bozr16/j119/xY0bN7Bs2TLpA1xTUlLKu0TY2trC1NS0vMvQCoaZV5DL5XBwcEDVqlXRqFEj/Oc//8Eff/yBnTt3YvXq1QCAefPmoV69ejAzM4OzszM+++wzZGRkSH28fJnpRYcOHYKhoSESExNV2oODg9GqVSttvSyiYhW851/8qly5MgDgk08+Qd++fVWWVygUsLGxwdq1awHkf/p2aGgo3N3dYWJiggYNGuD333+Xli84xbxz5054e3tDLpdj/fr10NPTw5kzZ1T6DgsLg6ura5FnQhcvXoz33ntPmo6IiIBMJsOyZcukNj8/P3zzzTfS9B9//IFGjRrB2NgY1atXx7Rp01SCVGpqKoYNGwZbW1tYWlriww8/RExMTLH76ubNm6hevTrGjh1brk8LpophzJgxMDIywp49e+Dr6wsXFxd07NgRe/fuxb179/Df//4XAJCdnY2vv/4azs7OkMvl8PT0xC+//CL1c+nSJXTu3BmWlpawsLBAq1atcPPmTQD5Z1b8/f1hY2MDKysr+Pr64uzZs9K6Qgh89913cHFxgVwuh5OTE8aPHy/Nf/kyU0JCArp27Qpzc3NYWlqiT58+Ko8GKri0um7dOri5ucHKygr9+vWTnpINALt27ULLli1RqVIlWFtbo3PnzlK9JcnMzISlpaXK7wgg/3g2MzNT2U5JGGbU9OGHH6JBgwbYtm0bAEBPTw8LFy7EpUuXsGbNGuzfvx+TJk0qVV+tW7dG9erVsW7dOqlNoVBgw4YNGDp0qFbqJ3pdAwYMwJ9//qkS1nfv3o2srCx0794dQP4T6deuXYtly5bh0qVLmDBhAgYOHIioqCiVviZPnozZs2fjypUr+Pjjj+Hn54fw8HCVZcLDwzF48GDo6RX+NeXr64vLly8jOTkZABAVFQUbGxscPHgQQP5xdPz4cbRp0wYAcPjwYQwaNAiff/45Ll++jOXLl2P16tWYOXOm1Gfv3r3x8OFD7Ny5E9HR0WjUqBHatWtX5H/U58+fR8uWLfHJJ59g8eLFGntALemmlJQU7N69G5999hlMTExU5jk4OGDAgAHYtGkThBAYNGgQfv31VyxcuBBXrlzB8uXLYW5uDgC4d+8eWrduDblcjv379yM6OhpDhw6VQvfTp08RGBiII0eO4MSJE6hRowY6deok/dHfunUr5s+fj+XLl+P69euIiIhAvXr1iqxZqVSia9euSElJQVRUFCIjI3Hr1q1C/7DcvHkTERER+Ouvv/DXX38hKioKs2fPluZnZmZi4sSJOHPmDPbt2wc9PT107969VMMxzMzM0K9fvyKP/V69esHCwqLEPiSCihQYGCi6du1a5Ly+ffuKOnXqFDlvy5YtwtraWpoODw8XVlZW0vS3334rGjRoIE3PmTNHpa+tW7cKc3NzkZGR8Ub1E6krMDBQ6OvrCzMzM5WvmTNnCiGEUCgUwsbGRqxdu1Zap3///qJv375CCCGeP38uTE1NxbFjx1T6DQoKEv379xdCCHHgwAEBQERERKgss2nTJlG5cmXx/PlzIYQQ0dHRQiaTibi4uCJrVSqVwtraWmzZskUIIUTDhg1FaGiocHBwEEIIceTIEWFoaCgyMzOFEEK0a9dOzJo1S6WPdevWCUdHRyGEEIcPHxaWlpbS9gt4eHiI5cuXCyH+79g9evSoqFy5svjxxx9L2qX0jjhx4oQAILZv317k/Hnz5gkA4uTJkwKAiIyMLHK5kJAQ4e7uLnJyckq13by8PGFhYSH+/PNPIYQQP/30k6hZs2ax67u6uor58+cLIYTYs2eP0NfXFwkJCdL8S5cuCQDi1KlTQoj897ypqalIT0+Xlvnqq69E06ZNi60pOTlZABAXLlwQQggRFxcnAIh///1XCPF/vwOePHkihBDi5MmTQl9fX9y/f18IIURSUpIwMDAQBw8eLNU+KMAzM69BCCH9J7Z37160a9cOVatWhYWFBT799FM8fvwYWVlZpepr8ODBuHHjBk6cOAEg/7JUnz59YGZmprX6iYrTtm1bnDt3TuVr1KhRAAADAwP06dMHGzZsAJD/H9kff/yBAQMGAABu3LiBrKws+Pv7w9zcXPpau3ZtodPOjRs3Vpnu1q0b9PX1sX37dgD5x0Hbtm3h5uZWZJ0ymQytW7fGwYMHkZqaisuXL+Ozzz5DdnY2rl69iqioKHzwwQfS+ICYmBhMnz5dpa7hw4fjwYMHyMrKQkxMDDIyMmBtba2yTFxcnErtCQkJ8Pf3x9SpU/HFF1+8+Q6nt4oo4XJjfHw89PX14evrW+T8c+fOoVWrVjA0NCxyflJSEoYPH44aNWrAysoKlpaWyMjIQEJCAoD8s4vPnj1D9erVMXz4cGzfvr3YMWlXrlyBs7MznJ2dpba6deuiUqVKuHLlitTm5uamcobE0dERDx8+lKavX7+O/v37o3r16rC0tJSO2YKaStKkSRN4eXlhzZo1AID169fD1dUVrVu3LtX6Bd6KZzOVtStXrsDd3R3x8fHo3LkzRo8ejZkzZ6JKlSo4cuQIgoKCkJOTU6qBVnZ2dujSpQvCw8Ph7u6OnTt3SqfKicqamZkZPD09i50/YMAA+Pr64uHDh4iMjISJiYl0t1PB5ae///4bVatWVVnv5efAvBzWjYyMMGjQIISHh6NHjx7YuHEjFixY8Mpa27RpgxUrVuDw4cN4//33YWlpKQWcqKgolT8YGRkZmDZtGnr06FGoH2NjY2RkZMDR0bHIY+/FMW+2trZwcnLCr7/+iqFDh8LS0vKVNdK7wdPTEzKZDFeuXJEuub7oypUrqFy5cqFLUC8raX5gYCAeP36MBQsWwNXVFXK5HM2aNUNOTg4AwNnZGbGxsdi7dy8iIyPx2Wef4YcffkBUVFSxAakkL68nk8lULiF16dIFrq6uWLlyJZycnKBUKvHee+9JNZXGsGHDsGTJEkyePBnh4eEYMmSI2pdueWZGTfv378eFCxfQs2dPREdHQ6lU4qeffoKPjw9q1qyJ+/fvq93nsGHDsGnTJqxYsQIeHh5o0aKFFionenPNmzeHs7MzNm3ahA0bNqB3797SL7u6detCLpcjISEBnp6eKl8v/vdXnGHDhmHv3r343//+h9zc3CKDx4sKxs1s2bJFGhvTpk0b7N27F0ePHpXaAKBRo0aIjY0tVJenpyf09PTQqFEjJCYmwsDAoNB8GxsbqR8TExP89ddfMDY2RkBAgFoDFOntZW1tDX9/f/zvf//Ds2fPVOYlJiZiw4YN6Nu3L+rVqwelUlloDFmB+vXr4/Dhw1AoFEXOP3r0KMaPH49OnTrBy8sLcrkcjx49UlnGxMQEXbp0wcKFC3Hw4EEcP34cFy5cKNRXnTp1cOfOHdy5c0dqu3z5MlJTU1G3bt1Sve7Hjx8jNjYW33zzDdq1a4c6dergyZMnpVr3RQMHDsTt27excOFCXL58GYGBgWr3wTDzCtnZ2UhMTMS9e/dw9uxZzJo1C127dkXnzp0xaNAgeHp6QqFQYNGiRbh16xbWrVuncjdFaQUEBMDS0hIzZszAkCFDtPBKiEqn4D3/4tfLvyw/+eQTLFu2DJGRkdIlJgCwsLDAl19+iQkTJmDNmjW4efMmzp49i0WLFkmnkF+lTp068PHxwddff43+/fuX+F9q/fr1UblyZWzcuFElzERERCA7O1vln4KpU6di7dq1mDZtGi5duoQrV67gt99+k+528vPzQ7NmzdCtWzfs2bMH8fHxOHbsGP773/8WusvKzMwMf//9NwwMDNCxY0eVAdH07lq8eDGys7MREBCAQ4cO4c6dO9i1axf8/f1RtWpVzJw5E25ubggMDMTQoUMRERGBuLg4HDx4EJs3bwYAjB07Funp6ejXrx/OnDmD69evY926dYiNjQUA1KhRA+vWrcOVK1dw8uRJDBgwQOU4Wb16NX755RdcvHgRt27dwvr162FiYgJXV9dC9fr5+aFevXoYMGAAzp49i1OnTmHQoEHw9fUtdBm4OJUrV4a1tTVWrFiBGzduYP/+/Zg4caLa+65y5cro0aMHvvrqK7Rv3x7VqlVTuw8OAC5GYGCgACAACAMDA2Frayv8/PzEqlWrRF5enrTcvHnzhKOjozAxMREBAQFi7dq1KoObShoAXGDKlCkqg6CIytqL7/kXv2rVqqWy3OXLlwUA4erqKpRKpco8pVIpwsLCRK1atYShoaGwtbUVAQEBIioqSghRePDfy3755ReVAYgl6dq1qzAwMBBPnz4VQuQPiKxcubLw8fEptOyuXbtE8+bNhYmJibC0tBRNmjQRK1askOanp6eLcePGCScnJ2FoaCicnZ3FgAEDpAGSLx+7T58+Fc2bNxetW7fmgH0SQggRHx8vAgMDhb29vfQeGjdunHj06JG0zLNnz8SECROEo6OjMDIyEp6enmLVqlXS/JiYGNG+fXthamoqLCwsRKtWrcTNmzeFEEKcPXtWNG7cWBgbG4saNWqILVu2qAzq3b59u2jatKmwtLQUZmZmwsfHR+zdu1fq+8VlhRDi9u3b4uOPPxZmZmbCwsJC9O7dWyQmJkrzi/p7NX/+fOHq6ipNR0ZGijp16gi5XC7q168vDh48qDIYuqQBwAX27dsnAIjNmzerudfzyYTgByRUBEFBQUhOTsaOHTvKuxSicvP9999jy5YtOH/+fHmXQkRlaN26dZgwYQLu378PIyMjtdfnAOBylpaWhgsXLmDjxo0MMvTOysjIQHx8PBYvXowZM2aUdzlEVEaysrLw4MEDzJ49GyNHjnytIANwzEy569q1K9q3b49Ro0bB39+/vMshKhdjx46Ft7c32rRpww+MJHqHzJ07F7Vr14aDgwNCQkJeux9eZiIiIiKdxjMzREREpNMYZoiIiEinMcwQERGRTmOYISIiIp3GMENEREQ6jWGGiIiIdBrDDBEREek0hhkiIiLSaQwzREREpNP+H0l9yUbOYAnaAAAAAElFTkSuQmCC\n"
                },
                "metadata": {}
              },
              {
                "output_type": "stream",
                "name": "stdout",
                "text": [
                  "📊 Frequency-Based Health Projection:\n"
                ]
              },
              {
                "output_type": "display_data",
                "data": {
                  "text/plain": "      Frequency Health Score Lungs Risk Liver Risk Life Expectancy\n0         Daily    100.0/100    Healthy    Healthy        82.1 yrs\n1    Every week     94.7/100    Healthy    Healthy        80.3 yrs\n2  Occasionally     92.0/100    Healthy    Healthy        80.1 yrs",
                  "text/html": "\n  <div id=\"df-ac184656-72ae-4b9b-b311-6ffd14edf98e\" class=\"colab-df-container\">\n    <div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Frequency</th>\n      <th>Health Score</th>\n      <th>Lungs Risk</th>\n      <th>Liver Risk</th>\n      <th>Life Expectancy</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Daily</td>\n      <td>100.0/100</td>\n      <td>Healthy</td>\n      <td>Healthy</td>\n      <td>82.1 yrs</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Every week</td>\n      <td>94.7/100</td>\n      <td>Healthy</td>\n      <td>Healthy</td>\n      <td>80.3 yrs</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Occasionally</td>\n      <td>92.0/100</td>\n      <td>Healthy</td>\n      <td>Healthy</td>\n      <td>80.1 yrs</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n    <div class=\"colab-df-buttons\">\n\n  <div class=\"colab-df-container\">\n    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-ac184656-72ae-4b9b-b311-6ffd14edf98e')\"\n            title=\"Convert this dataframe to an interactive table.\"\n            style=\"display:none;\">\n\n  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n  </svg>\n    </button>\n\n  <style>\n    .colab-df-container {\n      display:flex;\n      gap: 12px;\n    }\n\n    .colab-df-convert {\n      background-color: #E8F0FE;\n      border: none;\n      border-radius: 50%;\n      cursor: pointer;\n      display: none;\n      fill: #1967D2;\n      height: 32px;\n      padding: 0 0 0 0;\n      width: 32px;\n    }\n\n    .colab-df-convert:hover {\n      background-color: #E2EBFA;\n      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n      fill: #174EA6;\n    }\n\n    .colab-df-buttons div {\n      margin-bottom: 4px;\n    }\n\n    [theme=dark] .colab-df-convert {\n      background-color: #3B4455;\n      fill: #D2E3FC;\n    }\n\n    [theme=dark] .colab-df-convert:hover {\n      background-color: #434B5C;\n      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n      fill: #FFFFFF;\n    }\n  </style>\n\n    <script>\n      const buttonEl =\n        document.querySelector('#df-ac184656-72ae-4b9b-b311-6ffd14edf98e button.colab-df-convert');\n      buttonEl.style.display =\n        google.colab.kernel.accessAllowed ? 'block' : 'none';\n\n      async function convertToInteractive(key) {\n        const element = document.querySelector('#df-ac184656-72ae-4b9b-b311-6ffd14edf98e');\n        const dataTable =\n          await google.colab.kernel.invokeFunction('convertToInteractive',\n                                                    [key], {});\n        if (!dataTable) return;\n\n        const docLinkHtml = 'Like what you see? Visit the ' +\n          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n          + ' to learn more about interactive tables.';\n        element.innerHTML = '';\n        dataTable['output_type'] = 'display_data';\n        await google.colab.output.renderOutput(dataTable, element);\n        const docLink = document.createElement('div');\n        docLink.innerHTML = docLinkHtml;\n        element.appendChild(docLink);\n      }\n    </script>\n  </div>\n\n\n    </div>\n  </div>\n",
                  "application/vnd.google.colaboratory.intrinsic+json": {
                    "type": "dataframe",
                    "summary": "{\n  \"name\": \"update()\",\n  \"rows\": 3,\n  \"fields\": [\n    {\n      \"column\": \"Frequency\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"Daily\",\n          \"Every week\",\n          \"Occasionally\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Health Score\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"100.0/100\",\n          \"94.7/100\",\n          \"92.0/100\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Lungs Risk\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"Healthy\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Liver Risk\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"Healthy\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Life Expectancy\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"82.1 yrs\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
                  }
                },
                "metadata": {}
              },
              {
                "output_type": "stream",
                "name": "stdout",
                "text": [
                  "\n",
                  "✅ Recommendations:\n",
                  "Walk at least 3 km/day\n"
                ]
              },
              {
                "output_type": "display_data",
                "data": {
                  "text/plain": "<IPython.core.display.HTML object>",
                  "text/html": "<div style='background-color:black; padding:15px; border-radius:10px;'><h2 style='color:white'>💪 You're rocking it! Keep it up! 🚶 Move around more!</h2></div>"
                },
                "metadata": {}
              }
            ]
          }
        },
        "a3dc5ccf87204bf797dc6f8267cc3295": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "6c6d254ec5c14b4f900d511c4b4dccf0": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "975817a39d074a55bae6d8927d1ce064": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "8c1db63f3a2c470e901dd3c6619d362d": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "4d7de8763cde4fd0be732525524c4723": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "4f19800a19e34be383f6a6c8084d0d84": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "bf9f66c8b2544f0ba09c53280e596f62": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "11e8795f20ee42a084985223b27c746e": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "fea5d04c59ce483ba4bf8f4cecdf0a7b": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "b309b33ea6b54fb5bd8737aae5594009": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "4a0bb606160f41c39c2d18818a4c7235": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "a476e010c9954c4cabef1484a1b7f0b0": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "43d4e74ddf92498eb7af196c73673d13": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "6ec341b4ef684dc4bf452c153e40b014": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "ea1d8da5a70440adad001b5318213c58": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "22d34bc7e073462ba6ea1bc901ddb0c4": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "8b4ecef94b1144a8ab215ee118766276": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "b6602729a09c43f387facd273c44297a": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        },
        "9a3fc70ecb7849d39f9476eb06bbe43c": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "SliderStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "SliderStyleModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": "",
            "handle_color": null
          }
        },
        "78a30b17d9244973b22f92cdbeb499e3": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": null,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": null,
            "align_items": null,
            "align_self": null,
            "border": null,
            "bottom": null,
            "display": null,
            "flex": null,
            "flex_flow": null,
            "grid_area": null,
            "grid_auto_columns": null,
            "grid_auto_flow": null,
            "grid_auto_rows": null,
            "grid_column": null,
            "grid_gap": null,
            "grid_row": null,
            "grid_template_areas": null,
            "grid_template_columns": null,
            "grid_template_rows": null,
            "height": null,
            "justify_content": null,
            "justify_items": null,
            "left": null,
            "margin": null,
            "max_height": null,
            "max_width": null,
            "min_height": null,
            "min_width": null,
            "object_fit": null,
            "object_position": null,
            "order": null,
            "overflow": null,
            "overflow_x": null,
            "overflow_y": null,
            "padding": null,
            "right": null,
            "top": null,
            "visibility": null,
            "width": null
          }
        }
      }
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/streetscape-inc/Project-BeeWell-A-health-tracker/blob/main/BeeWell.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# Install required libraries\n",
        "!pip install pandas scikit-learn matplotlib ipywidgets --quiet\n",
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from sklearn.ensemble import RandomForestRegressor\n",
        "from sklearn.preprocessing import MinMaxScaler\n",
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output, HTML\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# -----------------------------\n",
        "# Title and Subtitle\n",
        "# -----------------------------\n",
        "display(HTML(\"\"\"\n",
        "<div style='text-align:center; margin-bottom:20px;'>\n",
        "    <h1 style='font-size:60px; font-weight:bold; color:#ffcc00; margin:0'>BeeWell</h1>\n",
        "    <h3 style='font-size:25px; color:#ffffff; margin:0'>Your Hive of Wellness</h3>\n",
        "</div>\n",
        "\"\"\"))\n",
        "\n",
        "# -----------------------------\n",
        "# Step 1: Simulate Dataset\n",
        "# -----------------------------\n",
        "np.random.seed(42)\n",
        "n_samples = 500\n",
        "\n",
        "data = pd.DataFrame({\n",
        "    'age': np.random.randint(18, 65, n_samples),\n",
        "    'weight': np.random.randint(45, 120, n_samples),\n",
        "    'height': np.random.randint(150, 200, n_samples),\n",
        "    'cigarettes': np.random.randint(0, 30, n_samples),\n",
        "    'alcohol': np.random.randint(0, 10, n_samples),\n",
        "    'distance_km': np.random.uniform(0, 10, n_samples),\n",
        "    'sleep_hours': np.random.uniform(3, 9, n_samples),\n",
        "    'calories': np.random.randint(1200, 4000, n_samples),\n",
        "    'caffeine_mg': np.random.randint(0, 500, n_samples)\n",
        "})\n",
        "\n",
        "# Compute BMI\n",
        "data['bmi'] = data['weight'] / (data['height']/100)**2\n",
        "\n",
        "# Overall health score\n",
        "def health_score(row):\n",
        "    score = 100\n",
        "    score -= row['cigarettes'] * 1.5\n",
        "    score -= row['alcohol'] * 2\n",
        "    score += row['distance_km'] * 3\n",
        "    score += row['sleep_hours'] * 4\n",
        "    score -= max(0, (row['calories'] - 2500) * 0.02)\n",
        "    score -= row['caffeine_mg'] * 0.03\n",
        "    score -= (row['bmi'] - 22) * 0.5\n",
        "    score -= (row['age'] - 30) * 0.2\n",
        "    return np.clip(score, 0, 100)\n",
        "\n",
        "data['overall_health'] = data.apply(health_score, axis=1)\n",
        "\n",
        "# -----------------------------\n",
        "# Step 2: Train overall health model\n",
        "# -----------------------------\n",
        "X = data[['age','weight','height','bmi','cigarettes','alcohol','distance_km','sleep_hours','calories','caffeine_mg']]\n",
        "y_health = data['overall_health']\n",
        "\n",
        "scaler = MinMaxScaler()\n",
        "X_scaled = scaler.fit_transform(X)\n",
        "\n",
        "health_model = RandomForestRegressor(n_estimators=100, random_state=42)\n",
        "health_model.fit(X_scaled, y_health)\n",
        "\n",
        "# -----------------------------\n",
        "# Step 3: Prediction Function\n",
        "# -----------------------------\n",
        "def predict(age, weight, height, cigarettes, alcohol, distance_km, sleep_hours, calories, caffeine_mg):\n",
        "    bmi = weight / (height/100)**2\n",
        "    input_df = pd.DataFrame({\n",
        "        'age':[age], 'weight':[weight], 'height':[height], 'bmi':[bmi],\n",
        "        'cigarettes':[cigarettes], 'alcohol':[alcohol],\n",
        "        'distance_km':[distance_km], 'sleep_hours':[sleep_hours],\n",
        "        'calories':[calories], 'caffeine_mg':[caffeine_mg]\n",
        "    })\n",
        "    input_scaled = scaler.transform(input_df)\n",
        "\n",
        "    health_pred = health_model.predict(input_scaled)[0]\n",
        "\n",
        "    # Base lungs & liver risk\n",
        "    lungs_pred = 2 if cigarettes >= 15 else 1 if cigarettes >=1 else 0\n",
        "    alcohol_per_kg = alcohol / (weight/70)\n",
        "    liver_pred = 2 if alcohol_per_kg >= 0.1 else 1 if alcohol_per_kg >= 0.05 else 0\n",
        "\n",
        "    lungs_map = {0:'Healthy',1:'Mild Risk',2:'Severe Risk'}\n",
        "    liver_map = {0:'Healthy',1:'Mild Risk',2:'Severe Risk'}\n",
        "\n",
        "    # Frequency-based projection\n",
        "    frequencies = {\n",
        "        'Daily':1.0,\n",
        "        'Every week':1/7,\n",
        "        'Occasionally':1/30\n",
        "    }\n",
        "\n",
        "    freq_table = []\n",
        "    base_life = 80\n",
        "\n",
        "    for freq_name, freq_factor in frequencies.items():\n",
        "        # Include all lifestyle factors in frequency effect\n",
        "        health_year = health_pred\n",
        "        health_year -= freq_factor * (cigarettes*3 + alcohol*2 + max(0,(calories-2500)*0.02) + caffeine_mg*0.03)\n",
        "        health_year += freq_factor * (distance_km*3 + sleep_hours*4)\n",
        "        health_year = np.clip(health_year, 0, 100)\n",
        "\n",
        "        # Adjust lungs & liver risk\n",
        "        if freq_name == 'Daily':\n",
        "            lungs_risk_freq = 2 if cigarettes>0 else 0\n",
        "            liver_risk_freq = 2 if alcohol>0 else 0\n",
        "            risk_factor = (cigarettes*0.1 + alcohol*0.08)\n",
        "        elif freq_name == 'Every week':\n",
        "            lungs_risk_freq = 1 if lungs_pred>0 else 0\n",
        "            liver_risk_freq = 1 if liver_pred>0 else 0\n",
        "            risk_factor = (cigarettes*0.05 + alcohol*0.04)\n",
        "        else:\n",
        "            lungs_risk_freq = 0 if lungs_pred==0 else max(lungs_pred-1,0)\n",
        "            liver_risk_freq = 0 if liver_pred==0 else max(liver_pred-1,0)\n",
        "            risk_factor = (cigarettes*0.02 + alcohol*0.02)\n",
        "\n",
        "        # Life expectancy with frequency\n",
        "        life_exp = max(40, base_life - risk_factor*10 + freq_factor*(distance_km*0.2 + sleep_hours*0.3))\n",
        "\n",
        "        freq_table.append({\n",
        "            'Frequency':freq_name,\n",
        "            'Health Score':f\"{health_year:.1f}/100\",\n",
        "            'Lungs Risk':lungs_map[lungs_risk_freq],\n",
        "            'Liver Risk':liver_map[liver_risk_freq],\n",
        "            'Life Expectancy':f\"{life_exp:.1f} yrs\"\n",
        "        })\n",
        "\n",
        "    freq_df = pd.DataFrame(freq_table)\n",
        "\n",
        "    # Recommendations\n",
        "    recs = []\n",
        "    if cigarettes>0: recs.append(\"Avoid smoking completely\")\n",
        "    if alcohol>0: recs.append(\"Limit alcohol intake\")\n",
        "    if sleep_hours<7: recs.append(\"Sleep at least 7 hours/day\")\n",
        "    if distance_km<3: recs.append(\"Walk at least 3 km/day\")\n",
        "    if calories>2500: recs.append(\"Reduce daily calorie intake\")\n",
        "    if caffeine_mg>400: recs.append(\"Reduce caffeine intake\")\n",
        "    if bmi>24: recs.append(\"Work on BMI with diet/exercise\")\n",
        "    if bmi<18.5: recs.append(\"Increase BMI with healthy diet\")\n",
        "    if not recs: recs.append(\"Maintain your healthy lifestyle!\")\n",
        "\n",
        "    # Plot health by frequency\n",
        "    plt.figure(figsize=(6,3))\n",
        "    plt.plot(list(frequencies.keys()), [health_pred - freq_factor * (cigarettes*3 + alcohol*2 + max(0,(calories-2500)*0.02) + caffeine_mg*0.03) + freq_factor*(distance_km*3 + sleep_hours*4) for freq_factor in frequencies.values()],\n",
        "             marker='o', color='green')\n",
        "    plt.ylim(0,100)\n",
        "    plt.ylabel('Health Score')\n",
        "    plt.title('Projected Health by Frequency')\n",
        "    plt.grid(True)\n",
        "    plt.show()\n",
        "\n",
        "    return freq_df, recs, health_pred, bmi\n",
        "\n",
        "# -----------------------------\n",
        "# Step 4: Interactive Widgets\n",
        "# -----------------------------\n",
        "age_widget = widgets.IntSlider(min=18,max=80,value=25,description='Age')\n",
        "weight_widget = widgets.IntSlider(min=40,max=120,value=65,description='Weight kg')\n",
        "height_widget = widgets.IntSlider(min=140,max=200,value=170,description='Height cm')\n",
        "cig_widget = widgets.IntSlider(min=0,max=30,value=0,description='Cigarettes')\n",
        "alc_widget = widgets.IntSlider(min=0,max=10,value=0,description='Alcohol')\n",
        "dist_widget = widgets.FloatSlider(min=0,max=15,value=0,description='Distance km')\n",
        "sleep_widget = widgets.FloatSlider(min=0,max=12,value=7,description='Sleep hrs')\n",
        "cal_widget = widgets.IntSlider(min=1200,max=4000,value=2000,description='Calories')\n",
        "caff_widget = widgets.IntSlider(min=0,max=600,value=100,description='Caffeine mg')\n",
        "\n",
        "out = widgets.Output()\n",
        "\n",
        "def update(change=None):\n",
        "    with out:\n",
        "        clear_output(wait=True)\n",
        "        freq_df, recs, health_pred, bmi = predict(age_widget.value, weight_widget.value, height_widget.value,\n",
        "                                cig_widget.value, alc_widget.value, dist_widget.value,\n",
        "                                sleep_widget.value, cal_widget.value, caff_widget.value)\n",
        "        print(\"📊 Frequency-Based Health Projection:\")\n",
        "        display(freq_df)\n",
        "        print(\"\\n✅ Recommendations:\")\n",
        "        print(\"; \".join(recs))\n",
        "\n",
        "        # --- Big casual note ---\n",
        "        avg_health = np.mean([float(s.split(\"/\")[0]) for s in freq_df['Health Score']])\n",
        "        note = \"\"\n",
        "        if avg_health >= 85:\n",
        "            note = \"💪 You're rocking it! Keep it up!\"\n",
        "        elif avg_health >= 70:\n",
        "            note = \"👍 Not bad, but some tweaks can level you up.\"\n",
        "        elif avg_health >= 50:\n",
        "            note = \"⚠️ Take care! Small habits can make big difference.\"\n",
        "        else:\n",
        "            note = \"🚨 Health alert! Time to change your lifestyle ASAP!\"\n",
        "\n",
        "        # Add casual mentions of bad habits\n",
        "        if cig_widget.value > 0:\n",
        "            note += \" 🚭 Smoking is dragging you down!\"\n",
        "        if alc_widget.value > 2:\n",
        "            note += \" 🍷 Cut back on alcohol!\"\n",
        "        if sleep_widget.value < 7:\n",
        "            note += \" 💤 Sleep more!\"\n",
        "        if dist_widget.value < 3:\n",
        "            note += \" 🚶 Move around more!\"\n",
        "        if bmi > 24:\n",
        "            note += \" 🏋️‍♂️ Work on your BMI!\"\n",
        "        if bmi < 18.5:\n",
        "            note += \" 🍽️ Eat more healthy food!\"\n",
        "\n",
        "        # Display as big bold HTML note with white text on black background\n",
        "        display(HTML(f\"<div style='background-color:black; padding:15px; border-radius:10px;'><h2 style='color:white'>{note}</h2></div>\"))\n",
        "\n",
        "for w in [age_widget, weight_widget, height_widget, cig_widget, alc_widget, dist_widget,\n",
        "          sleep_widget, cal_widget, caff_widget]:\n",
        "    w.observe(update,'value')\n",
        "\n",
        "display(widgets.VBox([age_widget, weight_widget, height_widget, cig_widget, alc_widget, dist_widget,\n",
        "                      sleep_widget, cal_widget, caff_widget, out]))\n",
        "\n",
        "update()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 923,
          "referenced_widgets": [
            "24dddbe6ef3b42cabeb66a65c709cdd9",
            "4a8e4c3b1ee54534bd6168663f31eb33",
            "95d8d40102fb4c0ea44637c50d9d42ab",
            "900bb8461bc54ddc82fb14f4ffb22677",
            "0349a23dd15c485c84e33229cde8a117",
            "ab56a4dd426548e7b27a62495366a0b0",
            "2ff46169eb7f461c8d94d05e3b97bd90",
            "c7e71047d5ba4f9790642a8008fba261",
            "f9b32fc4c8d44c589e73e1f53d53cea6",
            "8aed3d62399f4af3a30d49e7efab3668",
            "6015dcf353b047fba9be86119250c890",
            "a3dc5ccf87204bf797dc6f8267cc3295",
            "6c6d254ec5c14b4f900d511c4b4dccf0",
            "975817a39d074a55bae6d8927d1ce064",
            "8c1db63f3a2c470e901dd3c6619d362d",
            "4d7de8763cde4fd0be732525524c4723",
            "4f19800a19e34be383f6a6c8084d0d84",
            "bf9f66c8b2544f0ba09c53280e596f62",
            "11e8795f20ee42a084985223b27c746e",
            "fea5d04c59ce483ba4bf8f4cecdf0a7b",
            "b309b33ea6b54fb5bd8737aae5594009",
            "4a0bb606160f41c39c2d18818a4c7235",
            "a476e010c9954c4cabef1484a1b7f0b0",
            "43d4e74ddf92498eb7af196c73673d13",
            "6ec341b4ef684dc4bf452c153e40b014",
            "ea1d8da5a70440adad001b5318213c58",
            "22d34bc7e073462ba6ea1bc901ddb0c4",
            "8b4ecef94b1144a8ab215ee118766276",
            "b6602729a09c43f387facd273c44297a",
            "9a3fc70ecb7849d39f9476eb06bbe43c",
            "78a30b17d9244973b22f92cdbeb499e3"
          ]
        },
        "id": "CgTZ5AIZcPlD",
        "outputId": "89336a0f-03d0-4698-c217-81acefd2570c"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "<div style='text-align:center; margin-bottom:20px;'>\n",
              "    <h1 style='font-size:60px; font-weight:bold; color:#ffcc00; margin:0'>BeeWell</h1>\n",
              "    <h3 style='font-size:25px; color:#ffffff; margin:0'>Your Hive of Wellness</h3>\n",
              "</div>\n"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "VBox(children=(IntSlider(value=25, description='Age', max=80, min=18), IntSlider(value=65, description='Weight…"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "24dddbe6ef3b42cabeb66a65c709cdd9"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}